package com.example.demo.domain;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import lombok.Getter;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
@Entity
/* 모니터링 측정 툴
 */
public class QualityTool {
    @Id
    @SequenceGenerator(sequenceName = "qualitytool_seq", allocationSize = 1, name = "QUALITYTOOL_SEQ")
    @Schema(description = "Tool ID generated by sequence",  example = "0")
    Long id;

    @Schema(description = "Tool Serial No",  example = "31350132WS")
    String serial_no;

    @Schema(description = "Tool Name",  example = "Digital Multimeter")
    String tool_name;

    @Schema(description = "Tool Maker",  example = "FLUKE")
    String tool_maker;

    @Schema(description = "Tool Model",  example = "17B+")
    String tool_model;

    @Schema(description = "마지막 교정 일자",  example = "2024-02-01")
    Date last_calibration_date;

    @Schema(description = "마지막 교정 기관",  example = "교정기관")
    String last_calibration_org;

    @Schema(description = "차기 교정 일자",  example = "2025-02-01")
    Date next_calibration_date;

    @Schema(description = "툴 정보 업데이트한 사람",  example = "임꺽정")
    String updater;

    @Column(name = "UPDATE_DATE")
    @Schema(description = "툴 정보 업데이트 일자",  example = "2023-12-24")
    Date update_date;

    @Schema(description = "툴 처음 도입한 사람",  example = "홍길동")
    String first_register;

    @Column(name = "REGISTER_DATE")
    @Schema(description = "툴 도입일자",  example = "2023-12-24")
    Date register_date;
}
